### PR TITLE
fix: update Calendar Localization Issues in nepaliCalenderdata.ts and calendarLocalisations.ts

### PR DESCRIPTION
**Pull request by rc-poudel**
This pull request addresses two issues related to calendar localization:

nepaliCalenderdata.ts file for the year 2081
Current:
2081: [17, 31, 31, 32, 32, 31, 30, 30, 30, 29, 30, 30, 30]

Corrected:
2081: [17, 31, 32, 31, 32, 31, 30, 30, 30, 29, 30, 30, 30]

Issue in calendarLocalisations.ts:
Add 32 to the ne-NP numbers array.

error screenshot
Screenshot

solved screenshot
Screenshot 2024-06-24 at 07 44 01

Let me know if there are any questions or further adjustments needed.

### CODE REVIEW

**Review by kabaros — APPROVED** [review]
thanks @rc-poudel - One thing that came up during discussion with the Temporal team around Nepali calendar (and this kind of updates) is that they asked us to add a ticket for Nepali calendar to be added to the Unicode CLDR - they believe this should be straight forward for implementers (browsers, OS etc..) to follow on and implement. 

Here is the [disucssion](https://github.com/tc39/proposal-temporal/issues/2854#issuecomment-2162345582) - would you be interested in adding a ticket for Nepali as described, and following up on it? or recommend someone who could? (I can add the ticket, but I am not expert on the calendar itself so won't be able to answer calendar-specific questions). It would be great to see Nepali calendar natively supported by browsers at some point.

**Comment by kabaros** [comment]
@rc-poudel are you able to fix the conflicts in this PR (I htink just need to remove the change to package.json) and also update the commit message to follow our expected [format](https://www.conventionalcommits.org/en/v1.0.0/#examples), i.e. squash the commits and change the title to  something like `fix: update calendar data for year 2080 in nepali calendar`

**Comment by rc-poudel** [comment]
I have updated and fixing the conflicts on package.json

Please review and let me know if any further changes are needed.

as you know, our Nepali calendar system is different and needs a separate field for manipulation. I use the above package for display in the Capture app in DHIS2. If I have any new updates, I will let you know soon.

**Comment by kabaros** [comment]
@rc-poudel the build is still failing - all commits in the branch needs to follow the correct format .. it's probably easier to sqaush all commits into with the correct format.

image

**Pull request merged**
